version: "3.7"
services:
  db:
    image: postgres:12.5
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kairos_database_challenge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command:
      - "postgres"
volumes:
  postgres_data:
